site_name: GameKit
site_dir: dist
docs_dir: pages
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - Components: entity-components.md
  - UI: user-interface.md
  - Audio: audio.md
theme: mkdocs
markdown_extensions:
  - attr_list
extra_css:
  - css/custom.css
