site_name: GameKit
site_dir: dist
docs_dir: pages
nav:
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
      - Examples: tutorials/examples.md
  - Features:
      - Overview: features/overview.md
      - Application: features/application.md
      - Entities & Scenes: features/ecs.md
      - Entity Components:
          - Overview: features/components/overview.md
          - Transform: features/components/transform.md
          - Sprite: features/components/sprite.md
          - Animated Sprite: features/components/animated-sprite.md
          - RigidBody: features/components/rigidbody.md
          - Collider: features/components/collider.md
      - Rendering: features/rendering.md
      - Camera: features/camera.md
      - Input: features/input.md
      - File IO: features/file-io.md
      - Physics: features/physics.md
      - Audio:
          - Overview: features/audio/overview.md
          - Audio Clip: features/audio/audio-clip.md
theme: mkdocs
markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/page-config.js
