site_name: GameKit
site_dir: dist
docs_dir: pages
nav:
  - Tutorials:
    - Getting Started: tutorials/getting-started.md
    - Examples: tutorials/examples.md
  - Features:
      - Overview: features/overview.md
      - Application: features/application.md
theme: mkdocs
markdown_extensions:
  - attr_list
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/page-config.js
