name: Github Maven Publisher

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: kwameopareasiedu/gamekit-maven
          ref: master
          path: ./engine/target/mvn
          token: ${{ secrets.GAMEKIT_MAVEN_PAT }}
      - uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin
      - run: mvn --batch-mode deploy
#      - run: cp -r engine/target/reports/apidocs/ engine/target/mvn/docs/
      - run: |
          git config user.name publisher
          git config user.email publisher@gamekit.dev
          git add -A
          git commit -m "Published new version"
          git push origin master
        working-directory: ./engine/target/mvn