name: Publish Site

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node 22.22.3
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.3"
          registry-url: "https://registry.npmjs.org"
      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Get dependencies
        run: yarn install
        working-directory: site
      - name: Install firebase-tools
        run: |
          yarn global add firebase-tools@13.30.0
          firebase experiments:enable functionsv2deployoptimizations
        working-directory: site
      - name: Add firebase token to env
        run: echo "FIREBASE_TOKEN=${{secrets.FIREBASE_TOKEN}}" >> "$GITHUB_ENV"
        working-directory: site
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Build project
        run: yarn build
        working-directory: site
      - name: Deploy to firebase
        run: yarn deploy
        working-directory: site