name: Publish Site

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          registry-url: "https://registry.npmjs.org"
      - name: Get dependencies
        run: yarn install
        working-directory: site
      - name: Install firebase-tools
        run: |
          yarn global add firebase-tools@13.30.0
          firebase experiments:enable functionsv2deployoptimizations
        working-directory: site
      - name: Add firebase token to env
        run: echo "FIREBASE_TOKEN=${{secrets.FIREBASE_TOKEN}}" >> "$GITHUB_ENV"
        working-directory: site
      - name: Build project
        run: yarn build
        working-directory: site
      - name: Deploy to firebase
        run: yarn deploy:dev
        working-directory: site